### ISSUE TITLE
API: Enable Jaeger Compatible Format

### ISSUE THREAD

**Issue by jkrech17** [uptrace/uptrace#110]
Jaeger is still widely in use.  Enabling a method to write traces to Uptrace and retrieving them in Jaeger format could help migrate towards the Uptrace UI/interface.  This would prevent duplicate storage requirements from supporting Jaeger while transitioning to Uptrace and allow users to view traces within Grafana if needed.

Operations used in Grafana

```
/api/services
	=> /api/services
/api/operations
	=> /api/services/MyService/operations
/api/traces
	=> /api/traces?operation=/&service=test_service&start=1664979972328000&end=1664983572328000&lookback=custom
/traces/{trace_id}
	=> /api/traces/{trace_id}
```

Reference: https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v2/query.proto

**Comment by vmihailenco** [comment]
@jkrech17 a simpler alternative to support Grafana would be via Tempo API which is probably better supported withing Grafana. We even had this working at some [point](https://github.com/uptrace/uptrace/blob/a710f159fbcae1a96da8643eb848d2e53b2ffd64/pkg/tracing/tempo_handler.go), but it caused some dependency conflicts with Prometheus and was removed, but it should not be a problem any more since Prometheus API was removed too.

Everyone is wecome to try bringing the Tempo API back if you are interested.

**Comment by jkrech17** [comment]
> 

Hi,

The tempo API would work as well. I think I had tried it in the past but had an issue getting it to search services.  If we can put it back, I can test it out again and report any issues. 

Thanks!

**Comment by vmihailenco** [comment]
Okay, let's see if this is a popular request.
