### ISSUE TITLE
Wrong metrics - Cache issue on dashboard ?

### ISSUE THREAD

**Issue by stratdev3** [uptrace/uptrace#331]
Hi,

Second time i receive wrong alert from the filesystem metric dashboard.
I investigage and found something weird maybe cache issue ?

**The settings**
![image](https://github.com/uptrace/uptrace/assets/115271718/57021da4-e216-4c57-a588-30e3cf25dc7f)

**The dashboard with 15min steps, they are all false**
![image](https://github.com/uptrace/uptrace/assets/115271718/9b7fab4a-e674-4000-aaff-c694babf1e59)

**The same dashboard with 14 day steps, they are all correct**
![image](https://github.com/uptrace/uptrace/assets/115271718/2fb4c35c-cb23-4343-b5ce-4edb4fbdd477)

**Today, so 1 day after, the 15min step dashboard is finaly correct**
![image](https://github.com/uptrace/uptrace/assets/115271718/33aacdd3-4a31-4cc0-9792-2deb7ed30acf)

What cause the wrong metrics and so sending alert (false positive).

Thanks for your help

**Comment by vmihailenco** [comment]
On some of your screenshot the `free_space` column is `0`. That's why the `fs_util` is 100%. So for some reason the `free_space` metric is not reported or processed properly.

Are you you using Uptrace Cloud? How many timeseries approximately do you have?

**Comment by stratdev3** [comment]
I'm using Uptrace Cloud, `1.39GB/50GB` and  `694/2.5k timeseries`.

Few seconds between the 3 first screenshoots : 
- free_space is reporting 0 when 15min
- free_space is reporting 89G when 14 days

The settings show the number is `Last Value`, so why different last value ? It should be should be the same.

Notes :
- all "/" mount points are located on differents bare metal servers.
- i'm using otelcol-contrib as collector.

**Comment by vmihailenco** [comment]
Yesterday, around 17:00 GMT we had a delay in metrics processing, i.e. some metrics were processed with a delay. The incident lasted for about 1 hour. Could that explain it? I.e. you could see the described behavior at 17:00-18:00 GMT, but at 18:00 GMT it should have been working properly again.

Besides the obvious solution of not having such incidents in the first place, you can also configure "Allow NULL points" in the monitor settings. Then Uptrace won't create alerts when there are missing (NULL/NAN) points.

![null-points](https://github.com/uptrace/uptrace/assets/290976/ec2b1b08-1ef5-4d6a-ad9f-0ace7fa32046)

>free_space is reporting 89G when 14 days

When you chose 14 days, then we use a larger grouping interval (1+ hour) so that is why it works.

>The settings show the number is Last Value, so why different last value ? It should be the same.

It uses the last value from the sparkline. And sparkline is calculated using a different grouping interval.

**Comment by stratdev3** [comment]
> Yesterday, around 17:00 GMT we had a delay in metrics processing

That explains everything.

I will modify the missing points option like you propose. it will mitigate the next possible incident.

Thanks for your fast response time, explaination and for the uptrace opensource project.
One of my important tools from now.

**Comment by vmihailenco** [comment]
Thanks for reporting this and sorry for the inconvenience.
